### ISSUE TITLE
关于论文中的一些细节

### ISSUE THREAD

**Issue by bjtuxck** [xsc1234/BERM#1]
作者你好，最近阅读了BERM这篇论文，觉得idea非常好，并进行了一些尝试，遇到了一些问题，希望作者可以解答：
1. 原文中使用的对比学习损失函数，算余弦相似度时，向量是否进行了归一化处理？我看了一下提供的代码，好像没有进行这一步操作。
2. 交叉熵损失中使用了一正一负的样本配置，为什么不使用常见的一正n负配置，并且增加in-batch 的负样本呢？

以上两个问题希望作者抽空可以解答，祝好~

**Comment by xsc1234** [comment]
1. models.py第360行中对训练中对比学习损失函数的输入向量表示已经进行了norm操作。
2. 一正n负显存开销太大，因此我们用了一正一负，ANCE中对DPR的训练也是一正一负进行的。你如果GPU显存够大，可以尝试一正n负，一般会有更好的效果。
3. 没有在中文数据集上试过，效果未知。
